<style>
#title {
    text-align: center;
    font-family: Helvetica, Sans-serif;
}
#assign_name {
    text-align: center;
    font-size: 30px;
    font-weight: 200
}
#info {
    text-aling: left;
    font-size: 20px;
    font-weight: 200
}

</style>

<h1 id='title'>Actividad de Clase 1</h1> <style>
#title {
    text-align: center;
    font-family: Helvetica, Sans-serif;
}
#assign_name {
    text-align: center;
    font-size: 30px;
    font-weight: 200
}
#info {
    text-aling: left;
    font-size: 20px;
    font-weight: 200
}

</style>

<h1 id='title'>Actividad de Clase 1</h1> 
<p id='assign_name'>MovieLens</p>
<p id='info'>Por Sofía Maldonado García</p>
<p id='info'>Curso: Proyecto de Ciencia de Datos</p>
<p id='info'>Profesor: Cristian Zapata</p>

***
<p id='assign_name'>MovieLens</p>
<p id='info'>Por Sofía Maldonado García</p>
<p id='info'>Curso: Proyecto de Ciencia de Datos</p>
<p id='info'>Profesor: Cristian Zapata</p>

***

In [1]:
# Imports

import pandas as pd

In [7]:
# Importando datos como CSV

dflinks = pd.read_csv("data/links.csv")
dfmovies = pd.read_csv("data/movies.csv")
dfratings = pd.read_csv("data/ratings.csv")
dftags = pd.read_csv("data/tags.csv")

df = pd.merge(dflinks, dfmovies, how="left", on="movieId")
df = pd.merge(df, dfratings, how="left", on="movieId")
df = pd.merge(df, dftags, how="left", on="movieId")
df

,movieId,imdbId,tmdbId,title,genres,userId_x,rating,timestamp_x,userId_y,tag,timestamp_y
0,1,114709,862.0,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,1.0,4.0,9.649827e+08,336.0,pixar,1.139046e+09
1,1,114709,862.0,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,1.0,4.0,9.649827e+08,474.0,pixar,1.137207e+09
2,1,114709,862.0,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,1.0,4.0,9.649827e+08,567.0,fun,1.525286e+09
3,1,114709,862.0,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,5.0,4.0,8.474350e+08,336.0,pixar,1.139046e+09
4,1,114709,862.0,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,5.0,4.0,8.474350e+08,474.0,pixar,1.137207e+09
...,...,...,...,...,...,...,...,...,...,...,...
285778,193581,5476944,432131.0,Black Butler: Book of the Atlantic (2017),Action|Animation|Comedy|Fantasy,184.0,4.0,1.537109e+09,NaN,NaN,NaN
285779,193583,5914996,445030.0,No Game No Life: Zero (2017),Animation|Comedy|Fantasy,184.0,3.5,1.537110e+09,NaN,NaN,NaN
285780,193585,6397426,479308.0,Flint (2017),Drama,184.0,3.5,1.537110e+09,NaN,NaN,NaN
285781,193587,8391976,483455.0,Bungo Stray Dogs: Dead Apple (2018),Action|Animation,184.0,3.5,1.537110e+09,NaN,NaN,NaN
285782,193609,101726,37891.0,Andrew Dice Clay: Dice Rules (1991),Comedy,331.0,4.0,1.537158e+09,NaN,NaN,NaN

# EDA

In [10]:
df.describe()

,movieId,imdbId,tmdbId,userId_x,rating,timestamp_x,userId_y,timestamp_y
count,285783.000000,2.857830e+05,285770.000000,285762.000000,285762.000000,2.857620e+05,233234.000000,2.332340e+05
mean,14927.663741,2.956050e+05,12797.315320,313.894279,3.841270,1.214707e+09,470.681354,1.384754e+09
std,31402.673519,5.150156e+05,43479.255523,179.451387,1.020798,2.233730e+08,153.324249,1.534705e+08
min,1.000000,4.170000e+02,2.000000,1.000000,0.500000,8.281246e+08,2.000000,1.137179e+09
25%,296.000000,1.098300e+05,489.000000,160.000000,3.000000,1.019133e+09,424.000000,1.242494e+09
50%,1721.000000,1.125730e+05,680.000000,314.000000,4.000000,1.211377e+09,477.000000,1.457901e+09
75%,5673.000000,2.415270e+05,8963.000000,465.000000,4.500000,1.445346e+09,599.000000,1.498457e+09
max,193609.000000,8.391976e+06,525662.000000,610.000000,5.000000,1.537799e+09,610.000000,1.537099e+09

In [22]:
# Cuáles fueron las películas mejor rankeadas?

x = df.groupby(by="title", sort=False).sum()
x.sort_values("rating", ascending=False)

,movieId,imdbId,tmdbId,genres,userId_x,rating,timestamp_x,userId_y,tag,timestamp_y
title,,,,,,,,,,
Pulp Fiction (1994),16447832,6163047104,37785560.0,Comedy|Crime|Drama|ThrillerComedy|Crime|Drama|...,16402401.0,233218.5,6.320598e+13,32574542.0,good dialoguegreat soundtracknon-linearcult fi...,8.304271e+13
Fight Club (1999),34833348,1618920756,6474600.0,Action|Crime|Drama|ThrillerAction|Crime|Drama|...,3765798.0,50301.0,1.524233e+13,6835826.0,dark comedypsychologythought-provokingtwist en...,1.749694e+13
Star Wars: Episode IV - A New Hope (1977),1696760,500929234,71786.0,Action|Adventure|Sci-FiAction|Adventure|Sci-Fi...,1988584.0,27612.0,7.761248e+12,1519052.0,classicspace actionactionsci-fiEPICgreat sound...,9.241349e+12
Léon: The Professional (a.k.a. The Professional) (Léon) (1994),1363915,513972515,470155.0,Action|Crime|Drama|ThrillerAction|Crime|Drama|...,1413335.0,18707.5,5.491900e+12,2656542.0,assassinJean Renohit menActionassassinassassin...,6.845016e+12
Eternal Sunshine of the Spotless Mind (2004),32785894,1505509902,169252.0,Drama|Romance|Sci-FiDrama|Romance|Sci-FiDrama|...,1440342.0,18530.0,5.824436e+12,2288570.0,alternate realitymemorythought-provokingjim ca...,6.518901e+12
...,...,...,...,...,...,...,...,...,...,...
For All Mankind (1989),3338,97372,20423.0,Documentary,0.0,0.0,0.000000e+00,474.0,In Netflix queue,1.137202e+09
In the Realms of the Unreal (2004),92676,1170369,5559.0,Animation|DocumentaryAnimation|DocumentaryAnim...,0.0,0.0,0.000000e+00,954.0,AnimationDocumentaryHenry Darger,3.720476e+09
Chalet Girl (2011),85565,1487118,58232.0,Comedy|Romance,0.0,0.0,0.000000e+00,543.0,Comedy,1.377022e+09
"Innocents, The (1961)",1076,55018,16372.0,Drama|Horror|Thriller,0.0,0.0,0.000000e+00,474.0,governess,1.137521e+09
This Gun for Hire (1942),8765,35432,16703.0,Crime|Film-Noir|Thriller,0.0,0.0,0.000000e+00,474.0,In Netflix queue,1.137180e+09